Remove static due to build error
Need to remove static because of build error in current Fedora rawhide:
google_breakpad/client/linux/handler/exception_handler.cc:107:12: error: 'int tgkill(pid_t, pid_t, int)' was declared 'extern' and later 'static' [-fpermissive]